### ISSUE TITLE
Error React in Chat

### ISSUE THREAD

**Issue by Jaywrkr** [Call-for-Code/Solution-Starter-Kit-Cooperation-2020#72]
Everything is working fine.
The only problem I have is in the connection with the Assistant. I don't know if the error is related to React or in the server.

Possible Unhandled Promise Rejection (id: 0):
Error 

I'm falling in the Catch:
ERROR: Please try again. If the problem persists contact an administrator.

**Comment by Jaywrkr** [comment]
My error with ASSISTANT_URL=https://api.us-east.assistant.watson.cloud.ibm.com

**Comment by vabarbosa** [comment]
@Jaywrkr, since you closed the issue, are you all set?

**Comment by giacomobartoli** [comment]
@Jaywrkr @vabarbosa I am experiencing the same issue. How did you solve it?
Thanks

**Comment by vabarbosa** [comment]
@giacomobartoli what do you have set for your ASSISTANT_URL ?
can you confirm you are going here to get the credentials info:

![image](https://user-images.githubusercontent.com/13156555/80594031-3f935d00-89f0-11ea-8678-22bc8d7157c6.png)

and make sure you selected **API Details** and note the **Assistant ID** and **Api Key**. From the **Assistant URL**, make note of the base URL/domain (for example, `https://api.us-south.assistant.watson.cloud.ibm.com` or `https://api.eu-gb.assistant.watson.cloud.ibm.com`) but **do not** include the directory/path.

![image](https://user-images.githubusercontent.com/13156555/80594157-85e8bc00-89f0-11ea-9739-db85411e0762.png)
