### ISSUE TITLE
Chat not running

### ISSUE THREAD

**Issue by giacomobartoli** [Call-for-Code/Solution-Starter-Kit-Cooperation-2020#77]
I followed your instructions and I able to run the app and the server.
However, within the iOS app when I start the chat I get this error:

Possible Unhandled Promise Rejection (id: 0):
Error

I'm falling in the Catch:
ERROR: Please try again. If the problem persists contact an administrator.

Created a test.js for testing my Watson Assistant credentials and they are fine.

**Comment by giacomobartoli** [comment]
More info:

```
 LOG  Running "SolutionStarterKitCooperation2020App" with {"rootTag":1,"initialProps":{}}
 WARN  Possible Unhandled Promise Rejection (id: 0):
Error
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:112487:24
tryCallOne@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3244:16
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:3345:27
_callTimer@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30575:17
_callImmediatesPass@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30611:19
callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:30830:33
callImmediates@[native code]
__callImmediates@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2654:35
http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2431:34
__guard@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2637:15
flushedQueue@http://localhost:8081/index.bundle?platform=ios&dev=true&minify=false:2430:21
flushedQueue@[native code]
callFunctionReturnFlushedQueue@[native code]
 LOG  [Error]
```

**Comment by giacomobartoli** [comment]
SOLVED!
Make sure to:
1. Use correct base form URL (this depends on when the Assistant was created. Previous versions have different urls, while the new istances have something like https://api.eu-gb.assistant.watson.cloud.ibm.com)
2. Make sure you env variables (within .bash_profile) do not overwrite variables inside .env.

A suggestion: when the server app starts, it immediatly checks the connection with Cloudant. The same should be done with Watson Assistant.

**Comment by vabarbosa** [comment]
@giacomobartoli glad you got it resolved and that is a good suggestion. thanks.
@henrynash would you be able to implement @giacomobartoli suggestion. i.e., testing/trying connection with Watson Assistant on server start so any issues can be alerted to immediately instead of realizing it when trying to chat with the app

**Comment by giacomobartoli** [comment]
Thank you anyway @vabarbosa for your help.
@henrynash next week I'll be working a little bit on this demo. If you agree I can edit the behaviour as suggested (meaning checking the connection with Watson Assistant immediately) and open a PR.

**Comment by vabarbosa** [comment]
@giacomobartoli if you would like to open a PR that would be greatly appreciated.

**Comment by henrynash** [comment]
@gdequeiroz Excellent suggestion! I agree this would be a nice improvement. As @vabarbosa said, if you are able to create a PR for this, that would be great.

**Comment by giacomobartoli** [comment]
@vabarbosa @henrynash I am working on it. I give you news asap :-)

**Comment by giacomobartoli** [comment]
https://github.com/Call-for-Code/Solution-Starter-Kit-Cooperation-2020/pull/78
